#!/usr/bin/env bash
#==============================================================================
# Audit Logging Configuration Script
# Installs and configures auditd for security monitoring
#==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_DIR="/var/backups/linux-hardening"
LOG_DIR="/var/log/linux-hardening"
LOG_FILE="${LOG_DIR}/audit-logging-$(date +%Y%m%d-%H%M%S).log"
AUDIT_RULES_FILE="${SCRIPT_DIR}/../config/audit.rules"

DRY_RUN=false

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()   { echo -e "${GREEN}[+]${NC} $1" | tee -a "$LOG_FILE"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1" | tee -a "$LOG_FILE"; }
error() { echo -e "${RED}[-]${NC} $1" | tee -a "$LOG_FILE"; }
info()  { echo -e "${BLUE}[i]${NC} $1" | tee -a "$LOG_FILE"; }
header(){ echo -e "\n${BOLD}${CYAN}=== $1 ===${NC}\n" | tee -a "$LOG_FILE"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root."
        exit 1
    fi
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --rules-file) AUDIT_RULES_FILE="$2"; shift 2 ;;
            --dry-run)    DRY_RUN=true; shift ;;
            *)            error "Unknown option: $1"; exit 1 ;;
        esac
    done
}

install_auditd() {
    header "Installing Audit Daemon"

    if command -v auditctl &>/dev/null; then
        log "auditd is already installed"
        return 0
    fi

    info "Installing auditd..."

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would install auditd"
        return 0
    fi

    if command -v apt-get &>/dev/null; then
        apt-get update -qq && apt-get install -y -qq auditd audispd-plugins
    elif command -v yum &>/dev/null; then
        yum install -y -q audit audit-libs
    elif command -v dnf &>/dev/null; then
        dnf install -y -q audit audit-libs
    else
        error "Could not install auditd. Please install manually."
        return 1
    fi

    log "auditd installed successfully"
}

configure_auditd() {
    header "Configuring auditd"

    local auditd_conf="/etc/audit/auditd.conf"

    if [[ ! -f "$auditd_conf" ]]; then
        warn "auditd.conf not found at ${auditd_conf}"
        return 1
    fi

    # Backup existing config
    local backup_path="${BACKUP_DIR}/auditd.conf.bak.$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$BACKUP_DIR"
    cp -a "$auditd_conf" "$backup_path"
    log "Backed up auditd.conf to ${backup_path}"

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would configure auditd with hardened settings"
        return 0
    fi

    # Apply hardened configuration
    cat > "$auditd_conf" << 'EOF'
# Hardened auditd configuration
# Generated by Linux Hardening Suite

# Log file location
log_file = /var/log/audit/audit.log

# Log file permissions
log_group = adm
log_format = ENRICHED
write_logs = yes

# Log rotation
max_log_file = 50
max_log_file_action = ROTATE
num_logs = 20

# Dispatcher
dispatcher = /sbin/audispd
disp_qos = lossy

# Name resolution
name_format = HOSTNAME
name = auditd

# TCP listener (disable if not needed for remote logging)
tcp_listen_queue = 5
tcp_max_per_addr = 1
tcp_client_max_idle = 0
distribute_network = no

# Flush policy
freq = 50
flush = INCREMENTAL_ASYNC

# Priority
priority = 1

# End of file marker
end_of_event_timeout = 2
EOF

    chmod 640 "$auditd_conf"
    log "auditd configuration applied"
}

install_audit_rules() {
    header "Installing Audit Rules"

    local rules_dest="/etc/audit/rules.d/hardening.rules"

    if [[ ! -f "$AUDIT_RULES_FILE" ]]; then
        warn "Audit rules file not found: ${AUDIT_RULES_FILE}"
        return 1
    fi

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would install audit rules from ${AUDIT_RULES_FILE}"
        return 0
    fi

    mkdir -p /etc/audit/rules.d

    # Backup existing rules
    if [[ -f "$rules_dest" ]]; then
        local backup_path="${BACKUP_DIR}/audit-rules.bak.$(date +%Y%m%d-%H%M%S)"
        cp -a "$rules_dest" "$backup_path"
        log "Backed up existing audit rules to ${backup_path}"
    fi

    cp "$AUDIT_RULES_FILE" "$rules_dest"
    chmod 640 "$rules_dest"
    log "Audit rules installed to ${rules_dest}"

    # Load rules
    if augenrules --load 2>/dev/null; then
        log "Audit rules loaded successfully"
    elif auditctl -R "$rules_dest" 2>/dev/null; then
        log "Audit rules loaded via auditctl"
    else
        warn "Could not load audit rules. They will be loaded on next boot."
    fi
}

configure_log_rotation() {
    header "Configuring Audit Log Rotation"

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would configure log rotation"
        return 0
    fi

    cat > /etc/logrotate.d/audit << 'EOF'
/var/log/audit/audit.log {
    daily
    rotate 30
    compress
    delaycompress
    notifempty
    create 0600 adm adm
    sharedscripts
    postrotate
        /sbin/service auditd restart 2>/dev/null || true
    endscript
}
EOF

    chmod 644 /etc/logrotate.d/audit
    log "Log rotation configured"
}

verify_auditd() {
    header "Verifying Audit Daemon"

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would verify auditd is running"
        return 0
    fi

    # Enable and start auditd
    systemctl enable auditd 2>/dev/null || true

    if systemctl is-active --quiet auditd; then
        log "auditd is running"
    else
        systemctl start auditd 2>/dev/null || true
        if systemctl is-active --quiet auditd; then
            log "auditd started successfully"
        else
            warn "Failed to start auditd"
        fi
    fi

    # Verify rules are loaded
    local rule_count
    rule_count=$(auditctl -l 2>/dev/null | grep -v "^No rules" | wc -l || echo "0")
    info "Active audit rules: ${rule_count}"
}

print_summary() {
    header "Audit Logging Summary"
    echo -e "  Auditd Config: /etc/audit/auditd.conf"
    echo -e "  Audit Rules:   /etc/audit/rules.d/hardening.rules"
    echo -e "  Audit Log:     /var/log/audit/audit.log"
    echo -e "  Log File:      ${LOG_FILE}"

    echo -e "\n${CYAN}Useful commands:${NC}"
    echo -e "  View rules:    ${BOLD}auditctl -l${NC}"
    echo -e "  Search logs:   ${BOLD}ausearch -k <key>${NC}"
    echo -e "  Generate report:${BOLD}aureport${NC}"
}

main() {
    check_root
    parse_args "$@"

    mkdir -p "$BACKUP_DIR" "$LOG_DIR"
    chmod 700 "$BACKUP_DIR" "$LOG_DIR"

    echo -e "${BOLD}${CYAN}Audit Logging Module${NC}"
    log "Audit logging setup started at $(date)"

    install_auditd
    configure_auditd
    install_audit_rules
    configure_log_rotation
    verify_auditd
    print_summary

    log "Audit logging setup completed at $(date)"
    echo -e "\n${GREEN}Audit logging configured successfully.${NC}"
}

main "$@"
