#!/usr/bin/env bash
#==============================================================================
# Password Policy Hardening Script
# Enforces password complexity, aging, and lockout policies
#==============================================================================
set -euo pipefail

BACKUP_DIR="/var/backups/linux-hardening"
LOG_DIR="/var/log/linux-hardening"
LOG_FILE="${LOG_DIR}/password-policy-$(date +%Y%m%d-%H%M%S).log"

MIN_LENGTH=14
MAX_DAYS=90
MIN_DAYS=7
WARN_DAYS=14
REPEAT_LIMIT=4
MEMORY_SIZE=25
LOCKOUT_ATTEMPTS=5
LOCKOUT_TIME=900
DRY_RUN=false

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()   { echo -e "${GREEN}[+]${NC} $1" | tee -a "$LOG_FILE"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1" | tee -a "$LOG_FILE"; }
error() { echo -e "${RED}[-]${NC} $1" | tee -a "$LOG_FILE"; }
info()  { echo -e "${BLUE}[i]${NC} $1" | tee -a "$LOG_FILE"; }
header(){ echo -e "\n${BOLD}${CYAN}=== $1 ===${NC}\n" | tee -a "$LOG_FILE"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root."
        exit 1
    fi
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --min-length)       MIN_LENGTH="$2"; shift 2 ;;
            --max-age)          MAX_DAYS="$2"; shift 2 ;;
            --min-age)          MIN_DAYS="$2"; shift 2 ;;
            --warn-days)        WARN_DAYS="$2"; shift 2 ;;
            --lockout-attempts) LOCKOUT_ATTEMPTS="$2"; shift 2 ;;
            --lockout-time)     LOCKOUT_TIME="$2"; shift 2 ;;
            --dry-run)          DRY_RUN=true; shift ;;
            *)                  error "Unknown option: $1"; exit 1 ;;
        esac
    done
}

configure_login_defs() {
    header "Configuring /etc/login.defs"

    local login_defs="/etc/login.defs"

    if [[ ! -f "$login_defs" ]]; then
        warn "login.defs not found"
        return 1
    fi

    local backup_path="${BACKUP_DIR}/login.defs.bak.$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$BACKUP_DIR"
    cp -a "$login_defs" "$backup_path"
    log "Backed up login.defs to ${backup_path}"

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would apply the following settings:"
        echo -e "  PASS_MAX_DAYS   ${MAX_DAYS}"
        echo -e "  PASS_MIN_DAYS   ${MIN_DAYS}"
        echo -e "  PASS_MIN_LEN    ${MIN_LENGTH}"
        echo -e "  PASS_WARN_AGE   ${WARN_DAYS}"
        echo -e "  ENCRYPT_METHOD  SHA512"
        return 0
    fi

    # Update or add settings
    sed -i "s/^PASS_MAX_DAYS.*/PASS_MAX_DAYS   ${MAX_DAYS}/" "$login_defs"
    sed -i "s/^PASS_MIN_DAYS.*/PASS_MIN_DAYS   ${MIN_DAYS}/" "$login_defs"
    sed -i "s/^PASS_MIN_LEN.*/PASS_MIN_LEN    ${MIN_LENGTH}/" "$login_defs"
    sed -i "s/^PASS_WARN_AGE.*/PASS_WARN_AGE   ${WARN_DAYS}/" "$login_defs"

    # Ensure ENCRYPT_METHOD is set
    if grep -q "^ENCRYPT_METHOD" "$login_defs"; then
        sed -i "s/^ENCRYPT_METHOD.*/ENCRYPT_METHOD SHA512/" "$login_defs"
    else
        echo "ENCRYPT_METHOD SHA512" >> "$login_defs"
    fi

    # Ensure CREATE_HOME is set
    if grep -q "^CREATE_HOME" "$login_defs"; then
        sed -i "s/^CREATE_HOME.*/CREATE_HOME yes/" "$login_defs"
    else
        echo "CREATE_HOME yes" >> "$login_defs"
    fi

    log "login.defs updated with password policy settings"
}

configure_pam_password() {
    header "Configuring PAM Password Quality"

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would configure PAM password quality"
        return 0
    fi

    # Install pam_pwquality if not present
    if ! dpkg -l libpam-pwquality 2>/dev/null | grep -q "^ii" && \
       ! rpm -q pam 2>/dev/null | grep -q pam; then
        info "Installing password quality library..."
        if command -v apt-get &>/dev/null; then
            apt-get install -y -qq libpam-pwquality
        elif command -v yum &>/dev/null; then
            yum install -y -q pam
        elif command -v dnf &>/dev/null; then
            dnf install -y -q pam
        fi
    fi

    # Configure pwquality
    local pwquality_conf="/etc/security/pwquality.conf"
    if [[ -f "$pwquality_conf" ]]; then
        local backup_path="${BACKUP_DIR}/pwquality.conf.bak.$(date +%Y%m%d-%H%M%S)"
        cp -a "$pwquality_conf" "$backup_path"
    fi

    cat > "$pwquality_conf" << EOF
# Password Quality Configuration
# Generated by Linux Hardening Suite

# Minimum password length
minlen = ${MIN_LENGTH}

# Require at least one digit
dcredit = -1

# Require at least one uppercase letter
ucredit = -1

# Require at least one lowercase letter
lcredit = -1

# Require at least one special character
ocredit = -1

# Maximum consecutive characters in sequence
maxrepeat = 3

# Maximum consecutive same characters
maxclassrepeat = 3

# Check for dictionary words
dictcheck = 1

# Check if password contains user name
usercheck = 1

# Number of retries
retry = 3

# Size of credit for each character type
# (negative means required, positive means credit)
EOF

    chmod 644 "$pwquality_conf"
    log "PAM password quality configured at ${pwquality_conf}"

    # Configure pam_unix for password history
    local pam_common="/etc/pam.d/common-password"
    if [[ ! -f "$pam_common" ]]; then
        pam_common="/etc/pam.d/system-auth"
    fi

    if [[ -f "$pam_common" ]]; then
        local backup_path="${BACKUP_DIR}/$(basename "$pam_common").bak.$(date +%Y%m%d-%H%M%S)"
        cp -a "$pam_common" "$backup_path"

        # Ensure remember parameter is set (password history)
        if grep -q "pam_unix.so" "$pam_common"; then
            sed -i 's/.*pam_unix.so.*/password    sufficient    pam_unix.so remember=5 use_authtok sha512 shadow/' "$pam_common" 2>/dev/null || true
            log "PAM password history configured"
        fi
    fi
}

configure_account_lockout() {
    header "Configuring Account Lockout"

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would configure account lockout after ${LOCKOUT_ATTEMPTS} failed attempts"
        return 0
    fi

    # Configure pam_faillock
    local pam_auth="/etc/pam.d/common-auth"
    if [[ ! -f "$pam_auth" ]]; then
        pam_auth="/etc/pam.d/system-auth"
    fi

    if [[ -f "$pam_auth" ]]; then
        local backup_path="${BACKUP_DIR}/$(basename "$pam_auth").bak.$(date +%Y%m%d-%H%M%S)"
        cp -a "$pam_auth" "$backup_path"

        # Check if pam_faillock is available
        if pam_faillock --help &>/dev/null 2>&1; then
            # Configure faillock
            cat > /etc/security/faillock.conf << EOF
# Account Lockout Configuration
# Generated by Linux Hardening Suite

# Deny after this many failures
deny = ${LOCKOUT_ATTEMPTS}

# Lock time in seconds (0 = forever until admin unlocks)
unlock_time = ${LOCKOUT_TIME}

# Also lock root account (use with caution)
# even_root_user

# Audit failed login attempts
audit

# Fail delay in microseconds
fail_delay = 40000

# Directory to store failure records
dir = /var/run/faillock
EOF

            log "Account lockout configured: ${LOCKOUT_ATTEMPTS} attempts, ${LOCKOUT_TIME}s lockout"
        else
            warn "pam_faillock not available. Using pam_tally2 as fallback."
            # Fallback to pam_tally2
            cat > /etc/security/pam_tally2.conf << EOF
# Account Lockout (pam_tally2 fallback)
deny=${LOCKOUT_ATTEMPTS}
unlock_time=${LOCKOUT_TIME}
EOF
        fi
    fi
}

configure_password_history() {
    header "Configuring Password History"

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would configure password history (remember last 5 passwords)"
        return 0
    fi

    # Configure pam_pwhistory
    local pam_common="/etc/pam.d/common-password"
    if [[ ! -f "$pam_common" ]]; then
        pam_common="/etc/pam.d/system-auth"
    fi

    if [[ -f "$pam_common" ]]; then
        # Add pam_pwhistory if not present
        if ! grep -q "pam_pwhistory" "$pam_common"; then
            # Insert before pam_unix
            sed -i '/pam_unix.so/i password    required    pam_pwhistory.so remember=5 retry=3' "$pam_common" 2>/dev/null || true
            log "Password history (pam_pwhistory) configured"
        fi
    fi
}

set_password_defaults() {
    header "Setting Password Aging for Existing Accounts"

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would set password aging defaults"
        return 0
    fi

    local user_count=0

    while IFS=: read -r user _ uid _ _ _ shell; do
        if [[ $uid -ge 1000 && $user != "nobody" ]]; then
            # Set password aging
            chage -M "$MAX_DAYS" -m "$MIN_DAYS" -W "$WARN_DAYS" "$user" 2>/dev/null || true
            ((user_count++))
        fi
    done < /etc/passwd

    log "Password aging set for ${user_count} user accounts"
}

verify_policy() {
    header "Verifying Password Policy"

    info "Current password policy settings from login.defs:"
    echo -e "  PASS_MAX_DAYS:  ${BOLD}$(grep '^PASS_MAX_DAYS' /etc/login.defs | awk '{print $2}')${NC}"
    echo -e "  PASS_MIN_DAYS:  ${BOLD}$(grep '^PASS_MIN_DAYS' /etc/login.defs | awk '{print $2}')${NC}"
    echo -e "  PASS_MIN_LEN:   ${BOLD}$(grep '^PASS_MIN_LEN' /etc/login.defs | awk '{print $2}')${NC}"
    echo -e "  PASS_WARN_AGE:  ${BOLD}$(grep '^PASS_WARN_AGE' /etc/login.defs | awk '{print $2}')${NC}"
    echo -e "  ENCRYPT_METHOD: ${BOLD}$(grep '^ENCRYPT_METHOD' /etc/login.defs | awk '{print $2}')${NC}"

    if [[ -f /etc/security/pwquality.conf ]]; then
        echo ""
        info "Password quality settings:"
        grep -v '^#' /etc/security/pwquality.conf | grep -v '^$' | while IFS= read -r line; do
            echo -e "  ${line}"
        done
    fi
}

print_summary() {
    header "Password Policy Summary"
    echo -e "  Minimum Length:      ${BOLD}${MIN_LENGTH}${NC}"
    echo -e "  Maximum Age:         ${BOLD}${MAX_DAYS} days${NC}"
    echo -e "  Minimum Age:         ${BOLD}${MIN_DAYS} days${NC}"
    echo -e "  Warning Days:        ${BOLD}${WARN_DAYS} days${NC}"
    echo -e "  Lockout Attempts:    ${BOLD}${LOCKOUT_ATTEMPTS}${NC}"
    echo -e "  Lockout Duration:    ${BOLD}${LOCKOUT_TIME}s${NC}"
    echo -e "  Log File:            ${LOG_FILE}"
}

main() {
    check_root
    parse_args "$@"

    mkdir -p "$BACKUP_DIR" "$LOG_DIR"
    chmod 700 "$BACKUP_DIR" "$LOG_DIR"

    echo -e "${BOLD}${CYAN}Password Policy Module${NC}"
    log "Password policy configuration started at $(date)"

    configure_login_defs
    configure_pam_password
    configure_account_lockout
    configure_password_history
    set_password_defaults
    verify_policy
    print_summary

    log "Password policy configuration completed at $(date)"
    echo -e "\n${GREEN}Password policy configured successfully.${NC}"
}

main "$@"
