#!/usr/bin/env bash
#==============================================================================
# SSH Hardening Script
# Secures the SSH daemon configuration
#==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_DIR="/var/backups/linux-hardening"
LOG_DIR="/var/log/linux-hardening"
LOG_FILE="${LOG_DIR}/ssh-hardening-$(date +%Y%m%d-%H%M%S).log"
CONFIG_FILE="${SCRIPT_DIR}/../config/sshd_config_custom"

SSH_PORT=2222
PERMIT_ROOT="no"
PASSWORD_AUTH="no"
PUBKEY_AUTH="yes"
MAX_AUTH_TRIES=3
LOGIN_GRACE_TIME=30
CLIENT_ALIVE_INTERVAL=300
CLIENT_ALIVE_COUNT_MAX=2
DRY_RUN=false

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()   { echo -e "${GREEN}[+]${NC} $1" | tee -a "$LOG_FILE"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1" | tee -a "$LOG_FILE"; }
error() { echo -e "${RED}[-]${NC} $1" | tee -a "$LOG_FILE"; }
info()  { echo -e "${BLUE}[i]${NC} $1" | tee -a "$LOG_FILE"; }
header(){ echo -e "\n${BOLD}${CYAN}=== $1 ===${NC}\n" | tee -a "$LOG_FILE"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root."
        exit 1
    fi
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --port)        SSH_PORT="$2"; shift 2 ;;
            --permit-root) PERMIT_ROOT="$2"; shift 2 ;;
            --password-auth) PASSWORD_AUTH="$2"; shift 2 ;;
            --dry-run)     DRY_RUN=true; shift ;;
            *)             error "Unknown option: $1"; exit 1 ;;
        esac
    done
}

backup_ssh_config() {
    local backup_path="${BACKUP_DIR}/sshd_config.bak.$(date +%Y%m%d-%H%M%S)"
    if [[ -f /etc/ssh/sshd_config ]]; then
        cp -a /etc/ssh/sshd_config "$backup_path"
        chmod 600 "$backup_path"
        log "Backed up SSH config to: ${backup_path}"
    else
        warn "No existing SSH config found at /etc/ssh/sshd_config"
    fi
}

apply_ssh_config() {
    header "Applying Hardened SSH Configuration"

    if [[ ! -f /etc/ssh/sshd_config ]]; then
        error "SSH configuration not found at /etc/ssh/sshd_config"
        exit 1
    fi

    backup_ssh_config

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would apply the following changes:"
        echo -e "  - Set Port to ${BOLD}${SSH_PORT}${NC}"
        echo -e "  - Set PermitRootLogin to ${BOLD}${PERMIT_ROOT}${NC}"
        echo -e "  - Set PasswordAuthentication to ${BOLD}${PASSWORD_AUTH}${NC}"
        echo -e "  - Set PubkeyAuthentication to ${BOLD}${PUBKEY_AUTH}${NC}"
        echo -e "  - Set MaxAuthTries to ${BOLD}${MAX_AUTH_TRIES}${NC}"
        echo -e "  - Set LoginGraceTime to ${BOLD}${LOGIN_GRACE_TIME}${NC}"
        echo -e "  - Set ClientAliveInterval to ${BOLD}${CLIENT_ALIVE_INTERVAL}${NC}"
        echo -e "  - Set ClientAliveCountMax to ${BOLD}${CLIENT_ALIVE_COUNT_MAX}${NC}"
        return 0
    fi

    local sshd_config="/etc/ssh/sshd_config"

    # Create a hardened drop-in config
    mkdir -p /etc/ssh/sshd_config.d
    local drop_in="/etc/ssh/sshd_config.d/99-hardening.conf"

    cat > "$drop_in" << EOF
# Generated by Linux Hardening Suite - $(date)
# SSH Hardening Configuration

Port ${SSH_PORT}
PermitRootLogin ${PERMIT_ROOT}
PasswordAuthentication ${PASSWORD_AUTH}
PubkeyAuthentication ${PUBKEY_AUTH}
MaxAuthTries ${MAX_AUTH_TRIES}
LoginGraceTime ${LOGIN_GRACE_TIME}
ClientAliveInterval ${CLIENT_ALIVE_INTERVAL}
ClientAliveCountMax ${CLIENT_ALIVE_COUNT_MAX}

# Disable unnecessary forwarding
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no

# Security hardening
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes
MaxSessions 3
MaxStartups 10:30:60
IgnoreRhosts yes
HostbasedAuthentication no
PermitUserEnvironment no
Compression no

# Strong cryptography
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Logging
SyslogFacility AUTH
LogLevel VERBOSE
Banner /etc/issue.net
EOF

    chmod 600 "$drop_in"
    log "Created hardened SSH config at ${drop_in}"

    # Ensure the Include directive exists in main config
    if ! grep -q "Include /etc/ssh/sshd_config.d/" "$sshd_config" 2>/dev/null; then
        # Check if sshd supports drop-in directory
        if sshd -V 2>&1 | grep -q "SSHD_CONFIG"; then
            echo "" >> "$sshd_config"
            echo "# Include drop-in configuration" >> "$sshd_config"
            echo "Include /etc/ssh/sshd_config.d/*.conf" >> "$sshd_config"
            log "Added Include directive to sshd_config"
        fi
    fi

    # Validate configuration
    if sshd -t 2>&1; then
        log "SSH configuration validation: PASSED"
    else
        error "SSH configuration validation: FAILED"
        error "Restoring backup..."
        rm -f "$drop_in"
        return 1
    fi

    # Restart SSH service
    if systemctl is-active --quiet sshd 2>/dev/null; then
        systemctl restart sshd
        log "Restarted SSH service"
    elif systemctl is-active --quiet ssh 2>/dev/null; then
        systemctl restart ssh
        log "Restarted SSH service"
    else
        warn "Could not detect SSH service. Please restart manually."
    fi
}

setup_fail2ban() {
    header "Configuring Fail2Ban"

    if ! command -v fail2ban-client &>/dev/null; then
        info "Fail2Ban not installed. Attempting to install..."
        if [[ "$DRY_RUN" == true ]]; then
            info "DRY RUN: Would install fail2ban"
            return 0
        fi
        if command -v apt-get &>/dev/null; then
            apt-get update -qq && apt-get install -y -qq fail2ban
        elif command -v yum &>/dev/null; then
            yum install -y -q fail2ban
        elif command -v dnf &>/dev/null; then
            dnf install -y -q fail2ban
        else
            warn "Could not install fail2ban. Please install manually."
            return 1
        fi
    fi

    if [[ "$DRY_RUN" == true ]]; then
        info "DRY RUN: Would configure fail2ban jail for SSH"
        return 0
    fi

    cat > /etc/fail2ban/jail.local << EOF
[DEFAULT]
bantime  = 3600
findtime = 600
maxretry = 3
backend  = systemd
banaction = iptables-multiport

[sshd]
enabled = true
port    = ${SSH_PORT}
filter  = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime  = 3600
EOF

    systemctl enable fail2ban 2>/dev/null || true
    systemctl restart fail2ban 2>/dev/null || true
    log "Fail2Ban configured and started"
}

generate_key_reminder() {
    header "SSH Key Reminder"
    if [[ ! -f /root/.ssh/authorized_keys ]] || [[ ! -s /root/.ssh/authorized_keys ]]; then
        warn "No SSH authorized_keys found for root!"
        warn "Before disconnecting, ensure you have key-based access:"
        echo -e "  1. Generate key:  ${BOLD}ssh-keygen -t ed25519${NC}"
        echo -e "  2. Copy key:     ${BOLD}ssh-copy-id -p ${SSH_PORT} user@server${NC}"
        echo -e "  3. Test login:   ${BOLD}ssh -p ${SSH_PORT} user@server${NC}"
    fi
}

main() {
    check_root
    parse_args "$@"

    mkdir -p "$BACKUP_DIR" "$LOG_DIR"
    chmod 700 "$BACKUP_DIR" "$LOG_DIR"

    echo -e "${BOLD}${CYAN}SSH Hardening Module${NC}"
    log "SSH hardening started at $(date)"

    apply_ssh_config
    setup_fail2ban
    generate_key_reminder

    log "SSH hardening completed at $(date)"
    echo -e "\n${GREEN}SSH hardening complete. Test connectivity before closing this session!${NC}"
}

main "$@"
